/* Flow-IPC: Core
 * Copyright 2023 Akamai Technologies, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in
 * compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in
 * writing, software distributed under the License is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing
 * permissions and limitations under the License. */

/// @file
#pragma once

#include "ipc/transport/asio_local_stream_socket_fwd.hpp"
#include "ipc/util/shared_name_fwd.hpp"
#include "ipc/util/util_fwd.hpp"
#include <flow/util/util.hpp>
#include <boost/array.hpp>
#include <boost/asio/detail/buffer_sequence_adapter.hpp>

namespace ipc::transport::asio_local_stream_socket
{

// Constants.

/**
 * Our transport::asio_local_stream_socket utilities support transmitting at most this many native handles (FDs)
 * per single-message OS-call or batch-transmission per-message slot.
 *
 * ### Rationale: Current value ###
 * It is 1.  transport::asio_local_stream_socket utilities, while themselves opportunistically public, exist
 * in the first place to support sync_io::Native_socket_stream and derivative(s) which, formally speaking,
 * themselves implement concepts sync_io::Native_handle_sender and sync_io::Native_handle_receiver.  Those
 * APIs as of this writing permit at most 1 `Native_handle` to be transmitted per message.
 *
 * That could all change at some point; but for now this straightforwardly need only be 1.
 */
constexpr size_t N_PAYLOAD_FDS = 1;

// Types.

// Find doc headers near the bodies of these compound types.
union Msg_control_as_union;

// Free functions.

/**
 * Returns an #Endpoint corresponding to the given absolute Shared_name, so that an #Acceptor or #Peer_socket could
 * be bound to it.  TRACE logging possible; WARNING on error.
 *
 * @param logger_ptr
 *        Logger to use for subsequently logging.
 * @param absolute_name
 *        Name.
 * @param err_code
 *        See `flow::Error_code` docs for error reporting semantics.  #Error_code generated:
 *        one(s) generated by boost.asio; as of this writing at least:
 *        `boost::asio::error::name_too_long` (self-explanatory).
 * @return If it did not throw (which cannot happen if `err_code` non-null): default-cted `Endpoint` on error
 *         (if and only if `*err_code` truthy); the actual `Endpoint` otherwise (on success).
 * @tparam Protocol
 *         At least, `Protocol_byte_stream` or `Protocol_pkt_stream`.
 */
template<typename Protocol>
Endpoint<Protocol> endpoint_at_shared_name(flow::log::Logger* logger_ptr,
                                           const Shared_name& absolute_name, Error_code* err_code = nullptr);

} // namespace ipc::transport::asio_local_stream_socket
